### ISSUE TITLE
File_sets view is broken

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#327]
Views such as `concern/parent/<parent-id>/file_sets/<fileset-id>` are broken because there is no `permanent_url` for FileSet objects.  This is likely due to the change introduced in https://github.com/gwu-libraries/scholarspace-hyrax/commit/f0fde409e62524467735a1050e8526542d8b92a4

```
F, [2022-03-06T11:06:16.635605 #21016] FATAL -- : [6569357d-391b-4015-81d9-1d62e4a68d02]   
F, [2022-03-06T11:06:16.635698 #21016] FATAL -- : [6569357d-391b-4015-81d9-1d62e4a68d02] ActionView::Template::Error (undefined method `permanent_url' for #<Hyrax::FileSetPresenter:0x00007f47164b1b08>):
F, [2022-03-06T11:06:16.635796 #21016] FATAL -- : [6569357d-391b-4015-81d9-1d62e4a68d02]     14:               class: "btn btn-primary" %>
[6569357d-391b-4015-81d9-1d62e4a68d02]     15:   <% if Rails.configuration.respond_to?(:accessibility_url) %>
[6569357d-391b-4015-81d9-1d62e4a68d02]     16:     <p class="accessibility-form-link"/><%= link_to t('hyrax.accessibility.link_label'),
[6569357d-391b-4015-81d9-1d62e4a68d02]     17:       Rails.configuration.accessibility_url % {gwss_item_url: u(@presenter.permanent_url)},
[6569357d-391b-4015-81d9-1d62e4a68d02]     18:       id: "accessibility_form",
[6569357d-391b-4015-81d9-1d62e4a68d02]     19:       target: "_new" %>
[6569357d-391b-4015-81d9-1d62e4a68d02]     20:   <% end %> 
F, [2022-03-06T11:06:16.635839 #21016] FATAL -- : [6569357d-391b-4015-81d9-1d62e4a68d02]   
F, [2022-03-06T11:06:16.635873 #21016] FATAL -- : [6569357d-391b-4015-81d9-1d62e4a68d02] app/views/hyrax/file_sets/media_display/_pdf.html.erb:17:in `_app_views_hyrax_file_sets_media_display__pdf_html_erb__4130230125785887881_516620'
F, [2022-03-06T11:08:44.079222 #21016] FATAL -- : [3c5ee3e5-26f3-4481-b5c9-b0db30ab5439]   
F, [2022-03-06T11:08:44.079311 #21016] FATAL -- : [3c5ee3e5-26f3-4481-b5c9-b0db30ab5439] ActionView::Template::Error (undefined method `permanent_url' for #<Hyrax::FileSetPresenter:0x00005618bcab2478>):
F, [2022-03-06T11:08:44.079428 #21016] FATAL -- : [3c5ee3e5-26f3-4481-b5c9-b0db30ab5439]     14:               class: "btn btn-primary" %>
[3c5ee3e5-26f3-4481-b5c9-b0db30ab5439]     15:   <% if Rails.configuration.respond_to?(:accessibility_url) %>
[3c5ee3e5-26f3-4481-b5c9-b0db30ab5439]     16:     <p class="accessibility-form-link"/><%= link_to t('hyrax.accessibility.link_label'),
[3c5ee3e5-26f3-4481-b5c9-b0db30ab5439]     17:       Rails.configuration.accessibility_url % {gwss_item_url: u(@presenter.permanent_url)},
[3c5ee3e5-26f3-4481-b5c9-b0db30ab5439]     18:       id: "accessibility_form",
[3c5ee3e5-26f3-4481-b5c9-b0db30ab5439]     19:       target: "_new" %>
[3c5ee3e5-26f3-4481-b5c9-b0db30ab5439]     20:   <% end %> 
F, [2022-03-06T11:08:44.079491 #21016] FATAL -- : [3c5ee3e5-26f3-4481-b5c9-b0db30ab5439]   
F, [2022-03-06T11:08:44.079520 #21016] FATAL -- : [3c5ee3e5-26f3-4481-b5c9-b0db30ab5439] app/views/hyrax/file_sets/media_display/_pdf.html.erb:17:in `_app_views_hyrax_file_sets_media_display__pdf_html_erb__4130230125785887881_524500'
```

**Comment by kerchner** [comment]
Fixed in PR #328
